var ma = 
[".3gp", ".3g2", ".asf", ".wma", ".wmv", ".avi", ".divx", ".evo", ".f4v", ".flv", ".mkv", ".mk3d", ".mka", ".mks", ".webm", ".mcf", ".mp4", ".mpg", ".mpeg", ".m2p", ".m2ts", ".mxf", ".ogg", ".mov", ".mpeg", ".aac", ".mp3", ".rmvb", ".vob", ".ifo"];
var til = [
"Join for free: ",
"View girl profile: ",
"Click here: ",
"Pick me up: ",
"Enjoy with me: ",
"Follow me: ",
"Click me now: ",
"Lets get naughty: ",
"Check out here: ", 
"Live hot clips and webcams: ", 
"Looking for livesex tonight: ", 
"Meet hot girl for sex tonight: ", 
"Open live sex with hot girl: ", 
"Watch the hottest live shows: ", 
"Click here for live websex: ", 
"Girl Alone livesex in nude shows: ", 
"Find some the hottest girl: ", 
"Click for Live Snapsext With Me: ", 
"Hot live videos and photos: ",
"I'm so wet right now: ",
"contact me at this site: ",
"let's private chat with me here  ",
"I just got out of the shower: ",
"You make me so wet: ",
"Klick to open watch Video: ",
"contact me here:",
];
var stats = 
["J'ai manqué les caresses d'un homme, ce désir est insupportable.",
"Je ne peux pas envoyer ma vidéo nue sur Facebook, si vous voulez me regarder en vidéo nue.",
"Salut ...Vous cherchez quelqu'un chaude flirter avec ce soir? Rencontrez des célibataires dans votre ville, commencez un chat privé et organisez une date instantanément. ",
"si vous êtes un homme qui est solide et durable dans le sexe, je suis en attente pour votre arrivée avec joie.",
"Love taking a hard pumping in my ass. Get on your knees spread my cheeks wide and give my ass a good rimming. Shove your hard cock deep in me. Spoil me with a tip or gift it would make my day",
"I am hot, sweet, beautiful, with deep eyes and angelic face. I love to seduce, mock, play, enjoy and drive wild and hot!.",
"We could be so filthy together darling I want to see your cock, are you going to come through on webcam and show it to me?",
"Have you been dreaming about watching me playing with myself and flicking my plump clit nice and slowly just for you? ",
"Imagine all of my creamy pussy juices dripping down my legs and you can wank your cock for as long as you want?",
"Come and visit me babe, let's play and we can get dirty together all day (and all night if you want and you've got the energy,",
"Here are the newest and hottest porn video  I this week, coming from your mobile phone",
"very bad girl! can you see my photo? x oooh! hope I don't get caught! dirty f'ing bitch loves sex",
"Prob the most tattooed gorgeous, slim, sexy fucking body you'll ever see! Send me a text let's get it on",
"Love younger men, love playing. Also oral / anal. Text me now",
"im a super cute blonde, with dimples, small breasts, pretty face and sweet ass! x come and text me",
"hi all. looking to find some kind gentleman to have chats with. Hubby works away a lot. I get lonely",
"can I be your little fantasy? older guys def turn me on a lot! Love to be your special girl x text now",
"I have a boyfriend but looking for fun on the side. chat soon!",
"trainee legal secretary, slim. blonde, pretty xx . like fit guys, also like girls a bit. can we chat",
"where are all the horny f'ing guys? cum and get me now ",
"I'm a dirty little tease. You love it, I know I will! what u waiting for? Tell me your dirtiest ideas",
"Dirty big tits redhead that loves to suck and fuck in equal measure! Cum and get me guys ",
"hi, I'm into running and dance, love to sing. wanting guys to txt me. just can't stop playing! x help!",
"skinny, good boobs, white 18yr old. Living at home but up in my room and horny right now x anyone?",
"ok, totally new to this! hope to get texts from guys around here. I'm into anything, love dirty sex ",
"I'm busty, cute and prob a lil too cheeky! I live to have fun, got a rude pics for you too! message me.",
"posh, sexy, petite body, tanned, cute tits, gorgeous face. anal / oral/ casual / text only please any x.",
"love keep fit, have dark hair, tanned athletic body and cute face (I'm told!). Are there any guys.",
"Hey you! I'm a horny posh minx that turns into an animal in the sack. c'mon n txt me now.",
"blond, attractive, good body, love going out and keep fit, for guy similar. Txt chat see where we go.",
"I'm looking for flirty fun sexy guys. work all day and lonely at night. enjoy going out / staying in.",
"Hi all! x I'm a mature student with long brown hair, large boobs and a naughty sexual appetite! xx.",
"hey all, w midst girl, working in insurance, bored fuck less, txt me, make my day. let's get rude! xx.",
"Hey guys, looking for fun sexy chat with hot guys. Txt me now baby x feeling horny right now xxx.",
"Blonde, chubby tattoo's punk girl with an appetite for sexy fellas and horny girls too! lets chat xx.",
"have bf but bored and want more fun. mobile always wiv me so text and let's get it on. older is fine.",
"cutest lil thing you'll find on here. x mm, tight, shaved, petite, casual sex a must, no time for a bf.",
"skinny student with tats and big attitude. On the good side I'm a great fuck. hit me up guys x.",
"zany red head exhibitionist wanting to explore sexuality. Tell me what you'd do to me, older guy plz.",
"ive got to me your teen fantasy? tiny body, big tits, innocent face. Older guys welcome x no girls x.",
"Hope bf doesn't catch me on here! Devilishly naughty brunette looking for fun on the side. slim body.",
"Want to txt and see where it goes. Looking for older guys, i don't mind, txt me and see what happens x.",
"Hi, I'm short, cute asian girl, love all guys all backgrounds. like older men white men. xx xx xx xx.",
"am a sizzling hot firework in the bedroom! tight, cute, long brown hair, - you won't regret x txt me.",
"brunette housewife looking for discreet txt fun and maybe more. Love big strong men - I'm waiting xx.",
"I'm into most things sexually. looking to get more experience, message me and we can talk more xoxox.",
"Skinny cum whore xx do what you want with me, I love it, loving my cute tits and bod.txt me babe xx.",
"babe girl that loves talking dirty. Come on guys and girls. text me hunny. Anything goes.",
"Bored girlfriend, not getting any at home, guy for dirty chat and more. Love sex chat on phone xx.",
"girl gone bad! I want experienced guy to tell me all his dirty thoughts! I'll do same.",
"I'm just a very naughty girl x blonde hair, pretty and addicted to porn! help me guys plz, x ! xx.",
"bitch with tiny body and big appetite for sex. all shaved up and horny babe.",
"cute ass honey, love talking dirty. Guys you have my number now so txt me and let's see where it goes.",
"Very big tits, slim body, blonde hair, seeking guys for fun times.",
"Is anyone on here? Blonde, busty paralegal seeks sexy escape from the rat race. Love to talk fetish.",
"athletic petite body, small boobs, long hair. Love tall guys, think about sex all the time. help.",
"exploring my sexuality, girls or guys txt me. I want to know what turns you on. anything goes xxx.",
"I'm petite, pretty and looking for sexy fun. For 18 yrs old I'm pretty much into anything! try me xx.",
"hey there, hope you like my pic! bit naughty love dance, soul / clubs. Young guys for texting / fun.",
"am i too young to be showing naked pics?! at least u know what you're getting! x hope to get messages xx.",
"I'm a cheeky lil minx, petite sxy body n shaved. any guys round here want so fun? x txt me now hunny.",
"at college, plenty of time for chats with all them horny boos! are u into me? slim, cute, blond, sexy.",
"slim, pert boobs, long hair and pretty. Looking for guys to make contact. like keep fit and dance xx.",
"I'm looking to hook up with older men and be spoiled! I'm cute, petite, long brown hair, shaved, x txt x.",
"buxom big tits, long brown hair, constantly horny and wanting to get off. Who's on here? txt me xx.",
"I'm very slim, tiny tits, blonde hair! loll! love clubbing and shopping. Luvs older men x plz txt me x.",
"average. body size, big suck able boobies. am built for the ride. who wants a ride? loll x love you! xxxx.",
"open-minded, like younger men. text only, see where it goes.",
"took a pic of my pussy! naughty eh?! lol, txt my mobile so we can talk like black or white guys xoxx x.",
"med student needing to unwind. need fun fun, sex is my fav thing! fuck sake guys massage me please xxx.",
"I really shouldn't be doing this! . Want horny txt chat. so wet right now! fuk. boyfriend is out xxx.",
"horny black girl, 20, big black nipples and tight pussy for fun with black / white / asian guys xoxoxo xx.",
"blonde bored wife seeking fun in daytimes. Please bring some excitement to my life! anything goes xx.",
"Hello gentlemen. I'm a P/T vet assistant, married but wanting discreet sexy fun x message me now xx.",
"curvy, fun, I am a very broadminded woman with a sexy attitude . just like casual no strings fun x.",
"slim petite black girl for cheeky sex chat n more. Any guys in Liverpool area for horny fun? xxxxxxxxx.",
"I'm your perfect lil pixie! cute body, pretty and very naughty! cum find out x anything goes xx!.",
"hot blond for you! xx needing a guy to spice up my nights. Anyone on here? text me now, feel horny!.",
"what guys are on here? I love getting texts and love talking fucking dirty x so cum on.",
"any guys for horny chat tonight? in my room and feeling lonely - I know you want too! x mmmm baby x.",
"Ok so bit new to this! Up for sex chat and see where it goes. I'm in Birkenhead area. Always horny.",
"playful kitten with prefect body seeks man for night time fun x have a photo xxx any guys around.",
"HELLO BOYSS, VISIT MY WEBSITE AND WATCH MY PRIVATE SEX VIDEOS .",
"I want to wear something sexy, short and eye-catching to turn you on! Stockings and high heels maybe? It would be our secret - let me be your dessert",
"I need to give a good man some good tongue and you shake and vibrate. I do enjoy the same if you like sucking on pussy. I can be a good friend to or strictly pleasure.",
"I could either suck you dry or you could fuck me in as many positions as you want. I just want sex",
"I need my pussy eaten now I'm so honey my pussy hurts. My pussy is so wet and ready. I just want to cum all over your face. Please hurry up I'm ready now.",
"I'm single curvy female and now alone at home. I want some sex ting/dirty talk. It can be anonymous.",
"dark eyes and hair, stuck in boring marriage, there must be more than this?",
"looking for guys in the area. Just text me any time I will reply. have own place x",
"I am a hot and sweet girl ready for play with you.","I am a girl eager to fulfill their deepest desires in my sex","I am so passion, hot girl! I like give a pleasure!","A woman with the baser instincts, ready and your willingness","Hot & Stacked Long Legged Blonde I'm very nice but very naughty!","I'm ready to fulfill your fantasies and make you CUM hard","I'm pretty playful and sexy girl, forward intiresno guys","Hi pervs, let's get creepy! Bring on the taboo roleplay!","There is no limit to the sexxxy fun we can have","I`m lonely angel looking for heaven! And so so so hot.","im sexy and smart girl here for u) i like play whith all my hole","You should see me naked... I will totally blow Your mind!","Sexy girl inside ready for fun, to perform you a great show!","Come play with me! Your pleasure is always my command! ","I am a sexy blond with big DD boobs and a tight body.","Too innocent to be here, but inside lives wild animal!Wake it up","Blonde sassy petite looking for fun and ready to please","BETTER BRING YOUR TOOLS, I GOT A FEW HOLES THAT NEED PATCHING!","Im looking for fun. Arent you? Lets play bb! Im so hot and horny","If you want wildest expirience with hotest mature - welcome!","I will be your addiction, your Goddess, your only sense in life!","Please, be yourself and share all your desires with me","Dont be shy! I am a girl who like the sex every position.","I will please all my men as I am your slave. I will show you all","I love to naughty experiment and to learn something new. Let's do it ...","Come let me turn you on. I am ready to show you a good time","Very naughty and dirty perverted daring complacent.","I can be your lover, your best friend or your hidden sex fantasy.","Ready to squirt all over you and to fulfill your sex wild fantasies!","Vaginas are like weather. When it's wet, it's time to go inside.","Lets party all day and all night along! Discover me babe!","I am hot fire girl!I am young hot brunnet!I wait my horny guys!","I am everything you need to feel pleasure and satisfaction.","Please, be yourself and share all your desires with me.","Im a sexy full of passion young brunette. Lets have some fun!","i very like masturb , do u want to see me naked and play myself","Dont be shy! I am a girl who like the sex every position.","i have a sensual style, expressive eyes and a lovely smile","I'm a real fairy, making all of Your fantasies come true. Try me","The most sexy and hottie and squirter sugar baby of your dreams","I have no limits I be willing to do everything that you ask","I can be your wet saemaid from your hottest dreams :)","young, fresh and flirty play with me and i will make you happy","i am a shy and hot chick who wait fro u to come to here.","I am an exciting warm woman capable of having pleasure.","Sensual Sweetheart with the gift of Tease!~ Let's have some fun with me honey!","I'll give you what you've been craving for. Let's play!","Your naughty, southern sweetie. I love to tease and make you cum","Posh & kinky girl, yearming for the perfect orgasm!","How many licks does it take to make you cum? Let's find out! ^.-","show me how you do that trick, the one that makes me scream","show me how you do that trick, the one that makes me scream","Stunning & Seductive! Irresistible & Unforgettable!","Curvy, brown haired Sweetie ready to show you a good time!","I'm Young, Horny, And Eager To Get Naked For Everyone. ","I've Got A Rock Hard Body And I'm Not Afraid To Use It!","You should see me naked... I will totally blow Your mind!","Sexy girl inside ready for fun, to perform you a great show!","Good girl makes sure every meal has a happy ending..","Gorgeous hottie with sensual lips and amazing body will drive u","Im a lil naughty girl with crazy fantasies! Lets gave fun!","Modest sensual girl but for you I am ready to open my horisons","I am a cute lil redhead with a spunky personality!","Playful girl who loves to cream and cum..Amazing deals in here","A smartass and a badass, so it's pretty much about the ass!","I am a hot girl , and ready for make delicious things in the bed","Who doesn't love a funny girl who can look sexy at the same time","Sharing nice naughty pleasures with good gentleman...","Feel my soft skin with your touch and taste my sweet juicy lips!","If you are looking for the most gorgeous boobs, join me, my love","I am a passionate blonde loves to get fucked! waiting room will","I'm a hot brunette that will blow your mind away !","Please, be yourself and share all your desires with me.","If u been a bad boy I'll take my time on u...Enjoy","Sexxxy foxy curves, naughty ass and rose-pink boobs...","I will please all my men as I am your slave. I will show you all","I'm a hot young girl with big boobs who likes to play :)","So hot blondie with perfekt body - and i am so hard for you, man","I dream about romantic and sexy time with you! Get to know me!","Life's too short to spend it alone. Let's have a good time :*","i know my tits make u carzy very big and total nature","My Curvy Body is ready for you to make fantasies come true!","I'm a busty, playful teen with a very naughty imagination.","No idea what I'm doing but sometimes I get naked & people enjoy.","Hi my sweety .If u whant to see a greate and hot show come in",
];
var ui = ["\u0020\ud83d\udc9f","\u0020\ud83d\udc9d","\u0020\ud83d\udc98","\u0020\u2764","\u0020\ud83d\udc9b","\u0020\ud83d\udc9a","\u0020\ud83d\udc99","\u0020\ud83d\udc9c","\u0020\ud83d\udda4","\u0020\ud83d\udc95","\u0020\ud83d\udc9e","\u0020\ud83d\udc97","\u0020\ud83d\ude0d","\u0020\ud83d\ude18","\u0020\ud83d\udc44","\u0020\ud83d\udc8b","\u0020\ud83d\udc6f","\u0020\ud83d\udc8f","\u0020\ud83d\udc91","\u0020\ud83c\udf46","\u0020\ud83d\udd1e","\u0020\u2665"];
var u1 = ["\ud83d\udc91\ud83d\udc9f\u0020","\ud83d\ude3d\ud83d\udc8b\u0020","\ud83d\ude1c\ud83d\udc9e\u0020","\ud83d\udd25\ud83d\ude3d\u0020","\ud83d\ude46\ud83d\ude0d\u0020","\ud83c\udf08\ud83c\udf26\u0020","\ud83d\udd1e\ud83d\udcaf\u0020","\ud83d\udeb9\ud83d\udeba\u0020","\ud83d\udd38\ud83d\udd39\u0020","\ud83d\udc33\ud83d\ude3b\u0020","\ud83d\ude4f\ud83d\ude4c\u0020","\u2600\ud83d\udc3e\u0020","\ud83c\udf1e\ud83d\udc86\u0020","\ud83d\udc8f\ud83c\udf1f\u0020","\u2763\u2728\u0020"];
var u2 = ["\ud83d\udc49\ud83d\udc49\ud83d\udc49","\u27a1\u27a1\u27a1","\u23e9\u23e9\u23e9","\u25b6\u25b6\u25b6","\u23ed\u23ed\u23ed","\ud83d\udd05\ud83d\udd05\ud83d\udd05","\ud83d\udd1c\ud83d\udd1c\ud83d\udd1c","\ud83e\udd4a\ud83e\udd4a\ud83e\udd4a","\ud83d\ude4c\ud83d\ude4c\ud83d\ude4c","\ud83d\udc50\ud83d\udc50\ud83d\udc50","\ud83d\ude4f\ud83d\ude4f\ud83d\ude4f","\ud83d\udc4b\ud83d\udc4b\ud83d\udc4b"];
